RENAMED_COLUMNS = {
    'Province/State': 'province_state',
    'Country/Region': 'country',
    'Lat': 'lat',
    'Long': 'long',
}

# https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States_by_population#Summary_of_population_by_region
US_POPULATION = {
    'Massachusetts':        {'population': 6892503,  'sub_region': 'new_england',        'region': 'northeast'},
    'Connecticut':          {'population': 3565287,  'sub_region': 'new_england',        'region': 'northeast'},
    'New Hampshire':        {'population': 1359711,  'sub_region': 'new_england',        'region': 'northeast'},
    'Maine':                {'population': 1344212,  'sub_region': 'new_england',        'region': 'northeast'},
    'Rhode Island':         {'population': 1059361,  'sub_region': 'new_england',        'region': 'northeast'},
    'Vermont':              {'population': 623989,   'sub_region': 'new_england',        'region': 'northeast'},
    'New York':             {'population': 19453561, 'sub_region': 'mid_atlantic',       'region': 'northeast'},
    'Pennsylvania':         {'population': 12801989, 'sub_region': 'mid_atlantic',       'region': 'northeast'},
    'New Jersey':           {'population': 8882190,  'sub_region': 'mid_atlantic',       'region': 'northeast'},
    'Florida':              {'population': 21477737, 'sub_region': 'south_atlantic',     'region': 'south'},
    'Georgia':              {'population': 10617423, 'sub_region': 'south_atlantic',     'region': 'south'},
    'North Carolina':       {'population': 10488084, 'sub_region': 'south_atlantic',     'region': 'south'},
    'Virginia':             {'population': 8535519,  'sub_region': 'south_atlantic',     'region': 'south'},
    'Maryland':             {'population': 6045680,  'sub_region': 'south_atlantic',     'region': 'south'},
    'South Carolina':       {'population': 5148714,  'sub_region': 'south_atlantic',     'region': 'south'},
    'West Virginia':        {'population': 1792147,  'sub_region': 'south_atlantic',     'region': 'south'},
    'Delaware':             {'population': 973764,   'sub_region': 'south_atlantic',     'region': 'south'},
    'District of Columbia': {'population': 705749,   'sub_region': 'south_atlantic',     'region': 'south'},
    'Tenessee':             {'population': 6346105,  'sub_region': 'east_south_central', 'region': 'south'},
    'Alabama':              {'population': 4903185,  'sub_region': 'east_south_central', 'region': 'south'},
    'Kentucky':             {'population': 4467673,  'sub_region': 'east_south_central', 'region': 'south'},
    'Mississippi':          {'population': 2976149,  'sub_region': 'east_south_central', 'region': 'south'},
    'Texas':                {'population': 28995881, 'sub_region': 'west_south_central', 'region': 'south'},
    'Louisiana':            {'population': 4648794,  'sub_region': 'west_south_central', 'region': 'south'},
    'Oklahoma':             {'population': 3956971,  'sub_region': 'west_south_central', 'region': 'south'},
    'Arkansas':             {'population': 3017804,  'sub_region': 'west_south_central', 'region': 'south'},
    'Illinois':             {'population': 12671821, 'sub_region': 'east_north_central', 'region': 'midwest'},
    'Ohio':                 {'population': 11689100, 'sub_region': 'east_north_central', 'region': 'midwest'},
    'Michigan':             {'population': 9986857,  'sub_region': 'east_north_central', 'region': 'midwest'},
    'Indiana':              {'population': 6732219,  'sub_region': 'east_north_central', 'region': 'midwest'},
    'Wisconsin':            {'population': 5822434,  'sub_region': 'east_north_central', 'region': 'midwest'},
    'Missouri':             {'population': 6137428,  'sub_region': 'west_north_central', 'region': 'midwest'},
    'Minnesota':            {'population': 5639632,  'sub_region': 'west_north_central', 'region': 'midwest'},
    'Iowa':                 {'population': 3155070,  'sub_region': 'west_north_central', 'region': 'midwest'},
    'Kansas':               {'population': 2913314,  'sub_region': 'west_north_central', 'region': 'midwest'},
    'Nebraska':             {'population': 1934408,  'sub_region': 'west_north_central', 'region': 'midwest'},
    'South Dakota':         {'population': 884659,   'sub_region': 'west_north_central', 'region': 'midwest'},
    'North Dakota':         {'population': 762062,   'sub_region': 'west_north_central', 'region': 'midwest'},
    'Arizona':              {'population': 7278717,  'sub_region': 'mountain',           'region': 'west'},
    'Colorado':             {'population': 5758736,  'sub_region': 'mountain',           'region': 'west'},
    'Utah':                 {'population': 3205958,  'sub_region': 'mountain',           'region': 'west'},
    'Nevada':               {'population': 3080156,  'sub_region': 'mountain',           'region': 'west'},
    'New Mexico':           {'population': 2096829,  'sub_region': 'mountain',           'region': 'west'},
    'Idaho':                {'population': 1787065,  'sub_region': 'mountain',           'region': 'west'},
    'Montana':              {'population': 1068778,  'sub_region': 'mountain',           'region': 'west'},
    'Wyoming':              {'population': 578759,   'sub_region': 'mountain',           'region': 'west'},
    'California':           {'population': 39512223, 'sub_region': 'pacific',            'region': 'west'},
    'Washington':           {'population': 7614893,  'sub_region': 'pacific',            'region': 'west'},
    'Oregon':               {'population': 4217737,  'sub_region': 'pacific',            'region': 'west'},
    'Hawaii':               {'population': 1415872,  'sub_region': 'pacific',            'region': 'west'},
    'Alaska':               {'population': 731545,   'sub_region': 'pacific',            'region': 'west'}
}

# Everything but cruise ships that is associated with a US record
US_LOCATIONS_IN_SOURCE = [
    "Alabama",
    "Washington",
    "New York",
    "California",
    "Massachusetts",
    "Georgia",
    "Colorado",
    "Florida",
    "New Jersey",
    "Oregon",
    "Texas",
    "Illinois",
    "Pennsylvania",
    "Iowa",
    "Maryland",
    "North Carolina",
    "South Carolina",
    "Tennessee",
    "Virginia",
    "Arizona",
    "Indiana",
    "Kentucky",
    "District of Columbia",
    "Nevada",
    "New Hampshire",
    "Minnesota",
    "Nebraska",
    "Ohio",
    "Rhode Island",
    "Wisconsin",
    "Connecticut",
    "Hawaii",
    "Oklahoma",
    "Utah",
    "Kansas",
    "Louisiana",
    "Missouri",
    "Vermont",
    "Alaska",
    "Arkansas",
    "Delaware",
    "Idaho",
    "Maine",
    "Michigan",
    "Mississippi",
    "Montana",
    "New Mexico",
    "North Dakota",
    "South Dakota",
    "West Virginia",
    "Wyoming",
    "Kitsap, WA",
    "Solano, CA",
    "Santa Cruz, CA",
    "Napa, CA",
    "Ventura, CA",
    "Worcester, MA",
    "Gwinnett, GA",
    "DeKalb, GA",
    "Floyd, GA",
    "Fayette, GA",
    "Gregg, TX",
    "Monmouth, NJ",
    "Burlington, NJ",
    "Camden, NJ",
    "Passaic, NJ",
    "Union, NJ",
    "Eagle, CO",
    "Larimer, CO",
    "Arapahoe, CO",
    "Gunnison, CO",
    "Kane, IL",
    "Monroe, PA",
    "Philadelphia, PA",
    "Norfolk, VA",
    "Arlington, VA",
    "Spotsylvania, VA",
    "Loudoun, VA",
    "Prince George's, MD",
    "Pottawattamie, IA",
    "Camden, NC",
    "Pima, AZ",
    "Noble, IN",
    "Adams, IN",
    "Boone, IN",
    "Dane, WI",
    "Pierce, WI",
    "Cuyahoga, OH",
    "Weber, UT",
    "Bennington County, VT",
    "Carver County, MN",
    "Charlotte County, FL",
    "Cherokee County, GA",
    "Collin County, TX",
    "Jefferson County, KY",
    "Jefferson Parish, LA",
    "Shasta County, CA",
    "Spartanburg County, SC",
    "Harrison County, KY",
    "Johnson County, IA",
    "Berkshire County, MA",
    "Davidson County, TN",
    "Douglas County, OR",
    "Fresno County, CA",
    "Harford County, MD",
    "Hendricks County, IN",
    "Hudson County, NJ",
    "Johnson County, KS",
    "Kittitas County, WA",
    "Manatee County, FL",
    "Marion County, OR",
    "Okaloosa County, FL",
    "Polk County, GA",
    "Riverside County, CA",
    "Shelby County, TN",
    "St. Louis County, MO",
    "Suffolk County, NY",
    "Ulster County, NY",
    "Volusia County, FL",
    "Fairfax County, VA",
    "Rockingham County, NH",
    "Montgomery County, PA",
    "Alameda County, CA",
    "Broward County, FL",
    "Lee County, FL",
    "Pinal County, AZ",
    "Rockland County, NY",
    "Saratoga County, NY",
    "Charleston County, SC",
    "Clark County, WA",
    "Cobb County, GA",
    "Davis County, UT",
    "El Paso County, CO",
    "Honolulu County, HI",
    "Jackson County, OR ",
    "Jefferson County, WA",
    "Kershaw County, SC",
    "Klamath County, OR",
    "Madera County, CA",
    "Pierce County, WA",
    "Tulsa County, OK",
    "Douglas County, CO",
    "Providence County, RI",
    "Chatham County, NC",
    "Delaware County, PA",
    "Douglas County, NE",
    "Fayette County, KY",
    "Marion County, IN",
    "Middlesex County, MA",
    "Nassau County, NY",
    "Ramsey County, MN",
    "Washoe County, NV",
    "Wayne County, PA",
    "Yolo County, CA",
    "Santa Clara County, CA",
    "Clark County, NV",
    "Fort Bend County, TX",
    "Grant County, WA",
    "Santa Rosa County, FL",
    "Williamson County, TN",
    "New York County, NY",
    "Montgomery County, MD",
    "Suffolk County, MA",
    "Denver County, CO",
    "Summit County, CO",
    "Bergen County, NJ",
    "Harris County, TX",
    "San Francisco County, CA",
    "Contra Costa County, CA",
    "Orange County, CA",
    "Norfolk County, MA",
    "Maricopa County, AZ",
    "Wake County, NC",
    "Westchester County, NY",
    "Grafton County, NH",
    "Hillsborough, FL",
    "Placer County, CA",
    "San Mateo, CA",
    "Sonoma County, CA",
    "Umatilla, OR",
    "Fulton County, GA",
    "Washington County, OR",
    "Snohomish County, WA",
    "Humboldt County, CA",
    "Sacramento County, CA",
    "San Diego County, CA",
    "San Benito, CA",
    "Los Angeles, CA",
    "King County, WA",
    "Cook County, IL",
    "Skagit, WA",
    "Thurston, WA",
    "Island, WA",
    "Whatcom, WA",
    "Marin, CA",
    "Calaveras, CA",
    "Stanislaus, CA",
    "San Joaquin, CA",
    "Essex, MA",
    "Charlton, GA",
    "Collier, FL",
    "Pinellas, FL",
    "Alachua, FL",
    "Nassau, FL",
    "Pasco, FL",
    "Dallas, TX",
    "Tarrant, TX",
    "Montgomery, TX",
    "Middlesex, NJ",
    "Jefferson, CO",
    "Multnomah, OR",
    "Polk, OR",
    "Deschutes, OR",
    "McHenry, IL",
    "Lake, IL",
    "Bucks, PA",
    "Hanover, VA",
    "Lancaster, SC",
    "Sullivan, TN",
    "Johnson, IN",
    "Howard, IN",
    "St. Joseph, IN",
    "Knox, NE",
    "Stark, OH",
    "Anoka, MN",
    "Olmsted, MN",
    "Summit, UT",
    "Fairfield, CT",
    "Litchfield, CT",
    "Orleans, LA",
    "Pennington, SD",
    "Beadle, SD",
    "Charles Mix, SD",
    "Davison, SD",
    "Minnehaha, SD",
    "Bon Homme, SD",
    "Socorro, NM",
    "Bernalillo, NM",
    "Oakland, MI",
    "Wayne, MI",
    "New Castle, DE",
    "Puerto Rico",
    "Virgin Islands, U.S.",
]

CRUISE_SHIPS = [
    'Diamond Princess',
    'Grand Princess',
]
