    "Alabama":                'state',
    "Washington":             'state',
    "New York":               'state',
    "California":             'state',
    "Massachusetts":          'state',
    "Georgia":                'state',
    "Colorado":               'state',
    "Florida":                'state',
    "New Jersey":             'state',
    "Oregon":                 'state',
    "Texas":                  'state',
    "Illinois":               'state',
    "Pennsylvania":           'state',
    "Iowa":                   'state',
    "Maryland":               'state',
    "North Carolina":         'state',
    "South Carolina":         'state',
    "Tennessee":              'state',
    "Virginia":               'state',
    "Arizona":                'state',
    "Indiana":                'state',
    "Kentucky":               'state',
    "District of Columbia":   'state',
    "Nevada":                 'state',
    "New Hampshire":          'state',
    "Minnesota":              'state',
    "Nebraska":               'state',
    "Ohio":                   'state',
    "Rhode Island":           'state',
    "Wisconsin":              'state',
    "Connecticut":            'state',
    "Hawaii":                 'state',
    "Oklahoma":               'state',
    "Utah":                   'state',
    "Kansas":                 'state',
    "Louisiana":              'state',
    "Missouri":               'state',
    "Vermont":                'state',
    "Alaska":                 'state',
    "Arkansas":               'state',
    "Delaware":               'state',
    "Idaho":                  'state',
    "Maine":                  'state',
    "Michigan":               'state',
    "Mississippi":            'state',
    "Montana":                'state',
    "New Mexico":             'state',
    "North Dakota":           'state',
    "South Dakota":           'state',
    "West Virginia":          'state',
    "Wyoming":                'state',
